### ISSUE TITLE
[FEATURE] Adding new section and updating CSS with fonts, responsiveness, and enhancing Hover effect 

### ISSUE THREAD

**Issue by alienx5499** [ScrimbaBootcamp/community-garden#18]
• Want to add a new section for My favorite resources

• Updating the font-family

• Improving the hover effects with smooth background color transition and more 

• Enhancing responsiveness with new media queries for better layout on larger screens

• Adjusting font sizes and spacing for better readability

• Want to add box-shadow for enhanced visual depth

@michaella23 Can you please assign this issues to me ?

Thank You!

**Comment by michaella23** [comment]
Thanks for taking this on. 🙂
